export const metadata = {
  title: "New Head Meta Approach in 13.2+",
  description: "Generated by create next app",
};

export default function ExampleLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <h3>Example Nested Layout</h3>
      <body>{children}</body>
    </html>
  );
}
