import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <h1>New13</h1>
          <ul>
            <li>About</li>
            <li>Blog</li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
